class CreateForeignKeys < ActiveRecord::Migration
  def self.up
      add_foreign_key(:attachments, :plain_texts)
      add_foreign_key(:blocks, :pages)
      add_foreign_key(:blocks, :positions)
      add_foreign_key(:comments, :users)
      add_foreign_key(:gallery_photos, :galleries)
      add_foreign_key(:items, :blocks)
      add_foreign_key(:items, :users)
      add_foreign_key(:items, :statuses)
      add_foreign_key(:menus, :menu_types)
      add_foreign_key(:pages, :languages)
      add_foreign_key(:pages, :layout_templates)
      add_foreign_key(:pages, :users)
      add_foreign_key(:pages, :statuses)
      add_foreign_key(:positions, :layout_templates)
      add_foreign_key(:quotas, :languages)
      add_foreign_key(:roles_users, :roles)
      add_foreign_key(:roles_users, :users)
      add_foreign_key(:subevents, :events)
      add_foreign_key(:taggings, :tags)
      add_foreign_key(:training_module_events, :training_modules)
      add_foreign_key(:training_modules, :trainings)
      #add_foreign_key(:newsletter, :languages)
  end

  def self.down
      remove_foreign_key(:attachments, :plain_texts)
      remove_foreign_key(:blocks, :pages)
      remove_foreign_key(:blocks, :positions)
      remove_foreign_key(:comments, :users)
      remove_foreign_key(:gallery_photos, :galleries)
      remove_foreign_key(:items, :blocks)
      remove_foreign_key(:items, :users)
      remove_foreign_key(:items, :statuses)
      remove_foreign_key(:menus, :menu_types)
      remove_foreign_key(:pages, :languages)
      remove_foreign_key(:pages, :layout_templates)
      remove_foreign_key(:pages, :users)
      remove_foreign_key(:pages, :statuses)
      remove_foreign_key(:positions, :layout_templates)
      remove_foreign_key(:quotas, :languages)
      remove_foreign_key(:roles_users, :roles)
      remove_foreign_key(:roles_users, :users)
      remove_foreign_key(:subevents, :events)
      remove_foreign_key(:taggings, :tags)
      remove_foreign_key(:training_module_events, :training_modules)
      remove_foreign_key(:training_modules, :trainings)
      #remove_foreign_key(:newsletter, :languages)
  end
end
